
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class cars
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public cars()
    {

        this.cars_c_RFID = new HashSet<cars_c_RFID>();

        this.history_visit = new HashSet<history_visit>();

        this.list_access = new HashSet<list_access>();

    }


    public int id { get; set; }

    public string number_car { get; set; }

    public Nullable<int> chauffeur { get; set; }

    public Nullable<int> type_car { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<cars_c_RFID> cars_c_RFID { get; set; }

    public virtual chauffeurs chauffeurs { get; set; }

    public virtual type_car type_car1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<history_visit> history_visit { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<list_access> list_access { get; set; }

}

}
