//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_access
    {
        public int id { get; set; }
        public Nullable<int> number_car { get; set; }
        public Nullable<byte> status_access { get; set; }
    
        public virtual cars cars { get; set; }
    }
}
