//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SystemRFIDsEntities : DbContext
    {
        public SystemRFIDsEntities()
            : base("name=SystemRFIDsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cars> cars { get; set; }
        public virtual DbSet<cars_c_RFID> cars_c_RFID { get; set; }
        public virtual DbSet<chauffeurs> chauffeurs { get; set; }
        public virtual DbSet<history_visit> history_visit { get; set; }
        public virtual DbSet<list_access> list_access { get; set; }
        public virtual DbSet<RFID_metki> RFID_metki { get; set; }
        public virtual DbSet<status_active> status_active { get; set; }
        public virtual DbSet<type_car> type_car { get; set; }
    }
}
